### ISSUE TITLE
Stops working after few hours

### ISSUE THREAD

**Issue by nolafs** [Wildhoney/Magento-on-Angular#116]
Hi,

I notice the request returning a 500 error after a while. Only when cleaning the browser history, it starts working again. Any idea why this might happen?

Cheers
Olaf

**Comment by aonic** [comment]
Perhaps some invalid cookies or limits on your browser local storage

**Comment by nolafs** [comment]
It seems to happen any of my browsers. I am wondering if there is something magento locks.

**Comment by nolafs** [comment]
Hi,

It seems removing the cookies from your browser does make it work again. Here is the error I am getting the log files

[2017-01-12 09:01:14] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Symfony\Component\Debug\ExceptionHandler::createResponse() in /home/websites/technexion/public_html/corp/releases/20170111095247/web/app/themes/technexion-theme/products/api/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:155
Stack trace:
#0 /home/websites/technexion/public_html/corp/releases/20170111095247/web/app/themes/technexion-theme/products/api/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(98): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Mage_Core_Model_Session_Exception))
#1 /home/websites/technexion/public_html/corp/releases/20170111095247/web/app/themes/technexion-theme/products/api/app/Exceptions/Handler.php(49): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Mage_Core_Model_Session_Exception))
#2 /home/websites/technexion/public_html/corp/releases/20170111095247/web/app/themes/technexion-theme/products/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(281): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Mage_Core_Model_Session_Exception))
#3 /home/websites/technexion/public_html/corp/releases/20170111095247/web/app/themes/technexion-theme/products/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(91): Illuminate\Foundation\Http\Kernel->renderException(Object(Illuminate\Http\Request), Object(Mage_Core_Model_Session_Exception))
#4 /home/websites/technexion/public_html/corp/releases/20170111095247/web/app/themes/technexion-theme/products/api/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#5 {main}  

Cheers
Olaf
