### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by Tortschi** [Wildhoney/Magento-on-Angular#120]
Hello, i hope anyone can help me.

Node Version: 9.10.1
NPM Version: 5.6.0

`[4/7] ⠠ phantomjs: PhantomJS not found on PATH
error An unexpected error occurred: "/var/www/subshop/node_modules/phantomjs: Command failed.
Exit code: 1
Command: sh
Arguments: -c node install.js
Directory: /var/www/subshop/node_modules/phantomjs
Output:
PhantomJS not found on PATH
Phantom installation failed TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.join (path.js:1158:7)
    at findSuitableTempDirectory (/var/www/subshop/node_modules/phantomjs/install.js:127:30)
    at /var/www/subshop/node_modules/phantomjs/install.js:476:19
    at nextTickCallback (/var/www/subshop/node_modules/kew/kew.js:47:28)
    at process._tickCallback (internal/process/next_tick.js:112:11) TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.join (path.js:1158:7)
    at findSuitableTempDirectory (/var/www/subshop/node_modules/phantomjs/install.js:127:30)
    at /var/www/subshop/node_modules/phantomjs/install.js:476:19
    at nextTickCallback (/var/www/subshop/node_modules/kew/kew.js:47:28)
    at process._tickCallback (internal/process/next_tick.js:112:11)".`

Get when i have this Error.

**Comment by Tortschi** [comment]
https://gist.github.com/Tortschi/babfc48bf3f7ee427975ec1d352b4d93
