### ISSUE TITLE
Getting Started - unable to proceed due to errors

### ISSUE THREAD

**Issue by mystix** [Wildhoney/Magento-on-Angular#74]
I'm running node 0.10.26 + npm 1.4.7 (installed using mxcl/homebrew) on OSX 10.9.2.

Tried to get `moa` up and running using the instructions from the Getting Started section of the README, but kept encountering the following error during `npm install`:

```
> node-snapshot@0.3.15 postinstall /Users/mystix/git/Magento-on-Angular/node_modules/node-snapshot
> node_modules/bower/bin/bower install && node_modules/grunt-cli/bin/grunt build:production

>> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
>> Local Npm module "grunt-contrib-jshint" not found. Is it installed?
Warning: Task "uglify" not found. Use --force to continue.

Aborted due to warnings.
npm ERR! node-snapshot@0.3.15 postinstall: `node_modules/bower/bin/bower install && node_modules/grunt-cli/bin/grunt build:production`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the node-snapshot@0.3.15 postinstall script.
npm ERR! This is most likely a problem with the node-snapshot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/bower/bin/bower install && node_modules/grunt-cli/bin/grunt build:production
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-snapshot
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/mystix/git/Magento-on-Angular
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.7
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/mystix/git/Magento-on-Angular/npm-debug.log
npm ERR! not ok code 0
```

Managed to workaround this by changing the `dependencies` list in `package.json` to:

```
    // .... 

    "node-snapshot": "0.3.10" // anything >= 0.3.11 causes npm install to fail
  }
}
```

then tried to _Initialise the Node.js instance: node node/server.js;_ but encountered the following error:

```
➜  Magento-on-Angular git:(master) ✗ node node/server.js                                 

SyntaxError: Unexpected token u
    at Object.parse (native)
    at Request._callback (/Users/mystix/git/Magento-on-Angular/node/server.js:24:21)
    at self.callback (/Users/mystix/git/Magento-on-Angular/node_modules/request/request.js:122:22)
    at Request.EventEmitter.emit (events.js:95:17)
    at ClientRequest.self.clientErrorHandler (/Users/mystix/git/Magento-on-Angular/node_modules/request/request.js:231:10)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:440:14
    at /Users/mystix/git/Magento-on-Angular/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:177:31
```

Any ideas what I'm doing wrong?

**Comment by amit-elsner** [comment]
Hi,
Getting following error:

Error: _ is not defined
resolve@http://localhost/Fast/Magento-on-Angular/store/js/services/Gateway.js:36:13
contentUpdated/<@http://localhost/Fast/Magento-on-Angular/store/js/controllers/ProductsController.js:147:35
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost/Fast/Magento-on-Angular/store/bower_components/angular/angular.js:12811:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost/Fast/Magento-on-Angular/store/bower_components/angular/angular.js:12909:18
contentUpdated@http://localhost/Fast/Magento-on-Angular/store/js/controllers/ProductsController.js:143:13
EventEmitter.prototype.emit@http://localhost/Fast/Magento-on-Angular/store/bower_components/socket.io-client/dist/socket.io.js:633:7
SocketNamespace.prototype.onPacket@http://localhost/Fast/Magento-on-Angular/store/bower_components/socket.io-client/dist/socket.io.js:2248:9
Socket.prototype.onPacket@http://localhost/Fast/Magento-on-Angular/store/bower_components/socket.io-client/dist/socket.io.js:1930:5
Transport.prototype.onPacket@http://localhost/Fast/Magento-on-Angular/store/bower_components/socket.io-client/dist/socket.io.js:1332:5
Transport.prototype.onData@http://localhost/Fast/Magento-on-Angular/store/bower_components/socket.io-client/dist/socket.io.js:1303:11
WS.prototype.open/this.websocket.onmessage@http://localhost/Fast/Magento-on-Angular/store/bower_components/socket.io-client/dist/socket.io.js:2378:7

http://localhost/Fast/Magento-on-Angular/store/bower_components/angular/angular.js
Line 10126

Have a look in attached screenshot ! 
![magento-angular-js-error](https://cloud.githubusercontent.com/assets/7312006/9093859/6927d960-3b63-11e5-8854-d433f9cf1b6f.PNG)

**Comment by dixitxhtmljunkies** [comment]
Hi,
Getting following error:

Error: _ is not defined
resolve@http://localhost/Fast/Magento-on-Angular/store/js/services/Gateway.js:36:13
contentUpdated/<@http://localhost/Fast/Magento-on-Angular/store/js/controllers/ProductsController.js:147:35
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost/Fast/Magento-on-Angular/store/bower_components/angular/angular.js:12811:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost/Fast/Magento-on-Angular/store/bower_components/angular/angular.js:12909:18
contentUpdated@http://localhost/Fast/Magento-on-Angular/store/js/controllers/ProductsController.js:143:13
EventEmitter.prototype.emit@http://localhost/Fast/Magento-on-Angular/store/bower_components/socket.io-client/dist/socket.io.js:633:7
SocketNamespace.prototype.onPacket@http://localhost/Fast/Magento-on-Angular/store/bower_components/socket.io-client/dist/socket.io.js:2248:9
Socket.prototype.onPacket@http://localhost/Fast/Magento-on-Angular/store/bower_components/socket.io-client/dist/socket.io.js:1930:5
Transport.prototype.onPacket@http://localhost/Fast/Magento-on-Angular/store/bower_components/socket.io-client/dist/socket.io.js:1332:5
Transport.prototype.onData@http://localhost/Fast/Magento-on-Angular/store/bower_components/socket.io-client/dist/socket.io.js:1303:11
WS.prototype.open/this.websocket.onmessage@http://localhost/Fast/Magento-on-Angular/store/bower_components/socket.io-client/dist/socket.io.js:2378:7

http://localhost/Fast/Magento-on-Angular/store/bower_components/angular/angular.js
Line 10126

Have a look in attached screenshot ! 
![magento-angular-js-error](https://cloud.githubusercontent.com/assets/7312006/9093859/6927d960-3b63-11e5-8854-d433f9cf1b6f.PNG)

**Comment by Wildhoney** [comment]
`_` being undefined is due to the [Underscore dependency](https://github.com/Wildhoney/Magento-on-Angular/blob/master/bower.json#L17) not being included :+1:

**Comment by dixitxhtmljunkies** [comment]
Thank you @Wildhoney 

Its working now !

Currently code wrote upto cart. No logic for checkout right ?

**Comment by Wildhoney** [comment]
Sadly that's right &ndash; any pull requests relating to checkout gleefully merged!
