### ISSUE TITLE
composer install fail

### ISSUE THREAD

**Issue by ankurAuriga** [Wildhoney/Magento-on-Angular#98]
When running "composer install" command in api folder ,it fails by throwing following error 

PHP Fatal error:  Class 'Illuminate\Foundation\Console\TailCommand' not found in /var/www/html/moa/api/vendor/laravel/framework/src/Illuminate/Foundation/Providers/ArtisanServiceProvider.php on line 32
PHP Fatal error:  Class 'Symfony\Component\Debug\Exception\FatalErrorException' not found in /var/www/html/moa/api/vendor/laravel/framework/src/Illuminate/Exception/Handler.php on line 190

Please help as i am not able to use MOA.

**Comment by Wildhoney** [comment]
Hmm, @aonic Any ideas about what might be causing this?

**Comment by aonic** [comment]
@ankurAuriga can you try this:

// step 1
composer self-update

composer install

// step 2
composer dump-autoload

// step 3
php artisan clear-compiled

**Comment by ankurAuriga** [comment]
@aonic 
The problem is with composer install.This command is throwing the error.
Even if I am doing step 3 then also getting the same error.
PHP Fatal error:  Class 'Illuminate\Foundation\Console\TailCommand' not found in /var/www/html/moa/api/vendor/laravel/framework/src/Illuminate/Foundation/Providers/ArtisanServiceProvider.php on line 32
PHP Fatal error:  Class 'Symfony\Component\Debug\Exception\FatalErrorException' not found in /var/www/html/moa/api/vendor/laravel/framework/src/Illuminate/Exception/Handler.php on line 190

**Comment by aonic** [comment]
My research points to this being a version mismatch issue with composer.
That's why I recommended the self update

**Comment by ankurAuriga** [comment]
@aonic 
composer self update is successful and giving the below message:
You are already using composer version de65199f31fb27bfb595b14615a8b0f596b7dc5f.
But composer install is not running.

If PHP version could be issue then below is the php -v response

PHP 5.5.9-1ubuntu4 (cli) (built: Apr  9 2014 17:08:27) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies

**Comment by ankurAuriga** [comment]
It seems,error is with the laravel version.If I change the version to 5.0.\* in composer.json then got the different error 
 PHP Catchable fatal error:  Argument 1 passed to Illuminate\Foundation\Application::detectEnvironment() must be an instance of Closure, ar  
  ray given, called in /var/www/html/moa/api/bootstrap/start.php on line 31 and defined in /var/www/html/moa/api/vendor/laravel/framework/sr  
  c/Illuminate/Foundation/Application.php on line 431  

@aonic Any Help?

**Comment by timmen22** [comment]
Generating autoload files

> php artisan optimize
> PHP Warning:  Uncaught exception 'ErrorException' with message 'require_once(/Applications/XAMPP/xamppfiles/htdocs//app/Mage.php): failed to open stream: No such file or directory' in /Applications/XAMPP/xamppfiles/htdocs/moa/api/app/classes/Moa/API/Provider/MagentoProvider.php:32
> Stack trace:
> #0 /Applications/XAMPP/xamppfiles/htdocs/moa/api/app/classes/Moa/API/Provider/MagentoProvider.php(32): Illuminate\Exception\Handler->handleError(2, 'require_once(/A...', '/Applications/X...', 32, Array)
> #1 /Applications/XAMPP/xamppfiles/htdocs/moa/api/app/classes/Moa/API/Provider/MagentoProvider.php(32): Moa\API\Provider\MagentoProvider::__construct()
> #2 /Applications/XAMPP/xamppfiles/htdocs/moa/api/app/classes/Moa/Laravel/APIServiceProvider.php(34): Moa\API\Provider\MagentoProvider->__construct(Array)
> #3 /Applications/XAMPP/xamppfiles/htdocs/moa/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(498): Moa\Laravel\APIServiceProvider->Moa\Laravel{closure}(Object(Illuminate\Foundation\Application), Array)
> #4 /Applicat in /Applications/XAMPP/xamppfiles/htdocs/moa/api/app/classes/Moa/API/Provider/MagentoProvider.php on line 32
> PHP Fatal error:  Moa\API\Provider\MagentoProvider::__construct(): Failed opening required '/Applications/XAMPP/xamppfiles/htdocs//app/Mage.php' (include_path='/Applications/XAMPP/xamppfiles/htdocs/moa/api/vendor/phpseclib/phpseclib/phpseclib:.:/Applications/XAMPP/xamppfiles/lib/php') in /Applications/XAMPP/xamppfiles/htdocs/moa/api/app/classes/Moa/API/Provider/MagentoProvider.php on line 32
> {"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Moa\API\Provider\MagentoProvider::__construct(): Failed opening required '\/Applications\/XAMPP\/xamppfiles\/htdocs\/\/app\/Mage.php' (include_path='\/Applications\/XAMPP\/xamppfiles\/htdocs\/moa\/api\/vendor\/phpseclib\/phpseclib\/phpseclib:.:\/Applications\/XAMPP\/xamppfiles\/lib\/php')","file":"\/Applications\/XAMPP\/xamppfiles\/htdocs\/moa\/api\/app\/classes\/Moa\/API\/Provider\/MagentoProvider.php","line":32}}Script php artisan optimize handling the post-install-cmd event returned with an error

  [RuntimeException]  
  Error Output: PHP Warning:  Uncaught exception 'ErrorException' with messag  
  e 'require_once(/Applications/XAMPP/xamppfiles/htdocs//app/Mage.php): faile  
  d to open stream: No such file or directory' in /Applications/XAMPP/xamppfi  
  les/htdocs/moa/api/app/classes/Moa/API/Provider/MagentoProvider.php:32  
  Stack trace:  
  #0 /Applications/XAMPP/xamppfiles/htdocs/moa/api/app/classes/Moa/API/Provid  
  er/MagentoProvider.php(32): Illuminate\Exception\Handler->handleError(2, 'r  
  equire_once(/A...', '/Applications/X...', 32, Array)  
  #1 /Applications/XAMPP/xamppfiles/htdocs/moa/api/app/classes/Moa/API/Provid  
  er/MagentoProvider.php(32): Moa\API\Provider\MagentoProvider::__construct()  
  #2 /Applications/XAMPP/xamppfiles/htdocs/moa/api/app/classes/Moa/Laravel/AP  
  IServiceProvider.php(34): Moa\API\Provider\MagentoProvider->__construct(Arr  
  ay)  
  #3 /Applications/XAMPP/xamppfiles/htdocs/moa/api/vendor/laravel/framework/s  
  rc/Illuminate/Container/Container.php(498): Moa\Laravel\APIServiceProvider-  

> Moa\Laravel{closure}(Object(Illuminate\Foundation\Application), Array)  
>   #4 /Applicat in /Applications/XAMPP/xamppfiles/htdocs/moa/api/app/classes/M  
>   oa/API/Provider/MagentoProvider.php on line 32  
>   PHP Fatal error:  Moa\API\Provider\MagentoProvider::__construct(): Failed o  
>   pening required '/Applications/XAMPP/xamppfiles/htdocs//app/Mage.php' (incl  
>   ude_path='/Applications/XAMPP/xamppfiles/htdocs/moa/api/vendor/phpseclib/ph  
>   pseclib/phpseclib:.:/Applications/XAMPP/xamppfiles/lib/php') in /Applicatio  
>   ns/XAMPP/xamppfiles/htdocs/moa/api/app/classes/Moa/API/Provider/MagentoProv  
>   ider.php on line 32                                                          

Any Help?

**Comment by ammun-ree** [comment]
@ankurAuriga 
i think you have a problem with your config.son file , check the closure : magento provider , and the paths for your magento .
